# Generated by Django 2.2.4 on 2019-08-29 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='author',
        ),
        migrations.AddField(
            model_name='user',
            name='problems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city_problems.Problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='creation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_problems.Status'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.DateTimeField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_problems.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_problems.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('text', models.CharField(max_length=500)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_problems.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='votes',
            field=models.ManyToManyField(through='city_problems.Vote', to='city_problems.User'),
        ),
    ]
