# Generated by Django 2.2.4 on 2019-09-04 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_problems', '0003_auto_20190829_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='problems',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='city_problems.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='city_problems.User'),
            preserve_default=False,
        ),
    ]
