"""empty message

Revision ID: d0c68ec823f0
Revises: 9ecc5875c423
Create Date: 2019-07-21 02:48:27.664121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c68ec823f0'
down_revision = '9ecc5875c423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('short_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'short_name')
    # ### end Alembic commands ###
